name: Run Node.js Application on Schedule

on:
  schedule:
    - cron: '*/5 * * * *'  # Isso irá executar o workflow a cada 15 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Você pode alterar para a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Run your Node.js application
        run: node app.js  # Substitua com o comando correto para iniciar sua aplicação
